# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c787e4687c36c0605712da14d85e7c064d0241b851bb39b57fcdadb42e578aa3f389305fe46e3144072cf798fd99437a63055a8c36783e409301b5ae172b976e

test:
  secret_key_base: 6525df898ffd7a4d9ecc04204d86ad305a63125c0df84fdfccc11daf853f52833ee76bbedcf1c830cbe9bd0548b7defeb99daee3eaf6333d02c1cdf946e073ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
